* Hw-caesar.png

This image comes from the Portrait Gallery of the Perry–Castañeda Library of the University of Texas at Austin. According to the collection's title page, the image is in the public domain and no permission is needed to use it. The Library's Material Usage Statement indicates that it appreciates giving its website credit with the phrase: "Courtesy of the University of Texas Libraries, The University of Texas at Austin."

* Gaius_Julius_Caesar_(100-44_BC).JPG
This image comes from the Portrait Gallery of the Perry–Castañeda Library of the University of Texas at Austin. According to the collection's title page, the image is in the public domain and no permission is needed to use it.

The Library's Material Usage Statement indicates that it appreciates giving its website credit with the phrase: "Courtesy of the University of Texas Libraries, The University of Texas at Austin."
* Giulio-cesare-enhanced_1-800x1450.jpg
This work has been released into the public domain by its author, Wa at the German Wikipedia project. This applies worldwide.

In case this is not legally possible:
Wa grants anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
Photo by Andreas Wahra, first uploaded to de.wikipedia GiulioCesare.jpg. Modifications by Wolpertinger und Phrood.


    Deutsch: Die Büste von Gaius Julius Caesar im Archäologischen Nationalmuseum, Napoli. Fotografiert von Andreas Wahra im März 1997.
    English: Bust of Gaius Julius Caesar in the National Archaeological Museum of Naples. Taken by Andreas Wahra in March 1997.
    Italiano: Giulio Cesare (100-44 a.C.) - Busto (molto restaurato) già facente parte della Collezione Farnese, attualmente nel Museo Archeologico Nazionale di Napoli.
