* Hw-caesar.png
http://commons.wikimedia.org/wiki/File:Hw-caesar.png
This image comes from the Portrait Gallery of the Perry–Castañeda Library of the University of Texas at Austin. According to the collection's title page, the image is in the public domain and no permission is needed to use it. The Library's Material Usage Statement indicates that it appreciates giving its website credit with the phrase: "Courtesy of the University of Texas Libraries, The University of Texas at Austin."

* Gaius_Julius_Caesar_(100-44_BC).JPG
http://commons.wikimedia.org/wiki/File:Gaius_Julius_Caesar_(100-44_BC).JPG
This image comes from the Portrait Gallery of the Perry–Castañeda Library of the University of Texas at Austin. According to the collection's title page, the image is in the public domain and no permission is needed to use it.

The Library's Material Usage Statement indicates that it appreciates giving its website credit with the phrase: "Courtesy of the University of Texas Libraries, The University of Texas at Austin."
* Giulio-cesare-enhanced_1-800x1450.jpg
http://commons.wikimedia.org/wiki/File:Giulio-cesare-enhanced_1-800x1450.jpg
This work has been released into the public domain by its author, Wa at the German Wikipedia project. This applies worldwide.

In case this is not legally possible:
Wa grants anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
Photo by Andreas Wahra, first uploaded to de.wikipedia GiulioCesare.jpg. Modifications by Wolpertinger und Phrood.


    Deutsch: Die Büste von Gaius Julius Caesar im Archäologischen Nationalmuseum, Napoli. Fotografiert von Andreas Wahra im März 1997.
    English: Bust of Gaius Julius Caesar in the National Archaeological Museum of Naples. Taken by Andreas Wahra in March 1997.
    Italiano: Giulio Cesare (100-44 a.C.) - Busto (molto restaurato) già facente parte della Collezione Farnese, attualmente nel Museo Archeologico Nazionale di Napoli.
* ANUBIS.jpg
http://commons.wikimedia.org/wiki/File:ANUBIS.jpg
I, the copyright holder of this work, release this work into the public domain. This applies worldwide.
In some countries this may not be legally possible; if so:
I grant anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
* Louvre_032008_16.jpg
http://commons.wikimedia.org/wiki/File:Louvre_032008_16.jpg
Statue en bronze niellé d'or de la divine adoratrice Karomama, trouvée à Karnak - XXVIe dynastie égyptienne - Musée du Louvre
05/03/2008
Neithsabes (travail personnel / Casio EX-S500)
Licensing
Public domain 	I, the copyright holder of this work, release this work into the public domain. This applies worldwide.
In some countries this may not be legally possible; if so:
I grant anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
* Fayum-20.jpg
http://commons.wikimedia.org/wiki/File:Fayum-20.jpg
This image (or other media file) is in the public domain because its copyright has expired.

This applies to Australia, the European Union and those countries with a copyright term of life of the author plus 70 years.

Dialog-warning.svg You must also include a United States public domain tag to indicate why this work is in the public domain in the United States. Note that a few countries have copyright terms longer than 70 years: Mexico has 100 years, Colombia has 80 years, and Guatemala and Samoa have 75 years, Russia has 74 years for some authors. This image may not be in the public domain in these countries, which moreover do not implement the rule of the shorter term. Côte d'Ivoire has a general copyright term of 99 years and Honduras has 75 years, but they do implement the rule of the shorter term.
* Kilmacdough_Round_Tower.jpg
Description 	Kilmacdough_Round_Tower and Abbey, late evening view.
Date 	June 2010
Upload  19:25, 11 February 2011
Source 	Own work
Author 	Osioni
Permission
(Reusing this file) 	
Public domain 	I, the copyright holder of this work, release this work into the public domain. This applies worldwide.
In some countries this may not be legally possible; if so:
I grant anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
