Plot-Point-Kampagnen und nachhaltige Welten

* Was sind PPKs?

Plot Point Kampagnen sind mit Sawage Worlds groß geworden, oder haben zumindest größere Verbreitung erlangt (in Traveller gab es ähnliche Konzepte) und sie haben in der deutschen Netzgemeinde eine starke Anhängerschaft.

Sie sind vorlagen für episches, weltveränderndes Spiel, bei dem der SL grobe Hinweise gegeben werden, mit denen Sie ire Kampagne leiten kann.

Im Kleinen sind sie dadurch ähnlich wie Flyerbücher - was kaum verwundern sollte, wo doch Taysal ein anhänger von Sawage Worlds ist.

Im Großen dagegen unterscheiden sie sich dadurch, dass sie das dramatische Potenzial eines ganzen Settings freisetzen - und verbrauchen.
Zornhau schreibt dazu, dass Sawage Settings mit grober Feder gestrickt sind. Im Kontext dieses Textes könnte man das umformulieren als „Sawage Settings liefern nur die Hintergründe, die nötig sind, um ihre Plot Point Punkte Kampagne zu befeuern“. Und wenn die Kampagne durchgespielt ist, ist entsprechend auch der Hintergrund verbraucht.

Insofern ist hiermit der Hintergrund vollständig der Geschichte untergeordnet, so wie es auch in vielen Romanen passiert.

Für Pinnacle ist diese Stategie sehr geschickt, dadurch dass Welten mit klassischer Plot Punkte Kampagne nur so lange leben, bis die PPK gsspielt ist, wird das Regelwerk zum Fokuspunkt und es gibt stetigen Bedarf an neuen Veröffentlichungen. 

Gleichzeitig werden Settings zum Verbrauchsgegenstand, so dass nicht die Gefahr besteht, dass ein Setting größer wird als sein Regelwerk, was wiederum Sicherstellt, dass die Autoren von Sawage Worlds Hintergruünden an Sawage Worlds gebunden bleiben.

Allerdings ist das auch für die Autoren nützlich, denn ihre Arbeit wird zwar nur einmal erlebt, aber dafür haben ihre Fans Bedarf an weiteren Werken. Und das gibt Rollenspielen eine (weitere, kleine) kommerzielle Perspektive. Und das heißt, dass sie es (teilweise) finanziert kriegen, für Rollenspiele zu schreiben.

Im Endeffekt hat Pinnacle mit PPKs ein Extrem der Kräfteverteilung zwischen Welt und Regeln realisiert: Das Regelwerk als Spielform, zusammen mit Wegwerf-Welten.

* Was sind nachhaltige Welten

Das Gegenstück zu diesem Konzept sind Welten, die immer weiter verfeinert werden, um in der gleichen Welt immer neue Abenteuer und Spielformen finden. Das bekannteste Beispiel dafür ist in Deutschland DSA. Hier wird jeder Fleck der Welt detailliert ausgearbeitet, und diese Regionalbeschreibungen werden verkauft.
Hierdurch entwickelt sich eine immer intensivere Vorstellung der Welt, und wenn die einzelnen Beschreibungen konsistent sind (und gut gemacht), kann sich die Welt für die Spieler zu einer zweiten Heimat entwickeln. Durch dieses Heimatgefühl können dann kleinere Handlungen eine Bedeutung erlangen, die der Rettung der Welt entspricht, ohne aber die Welt zu zerstören. Die Kräfteverteilung zwischen Regeln und Welt ist hier gerade umgekehrt wie bei Plot-Punkte-Kampagnen: DSA-Spieler neigen eher dazu, die Regeln zu ändern (wie an mehreren DSA-Regeln-Klonen sichtbar wird), um das Gefühl von Aventurien zu transportieren, als an der Welt zu schrauben. Und die Pervertierung von beidem durch die Borbaradianer hat mir selbst sehr schwer im Magen gelegen - anders als bei jeglicher anderen Welt.

Außerdem können Spieler in der Welt mit den gleichen Charakteren immer neue Abenteuer erleben und dabei Stück für Stück eine immer stärkere Vorstellung der Welt und auch ihres Charakters aufbauen.

Insofert verkörpert DSA das andere Extrem: Die persistente Welt, vielleicht am stärksten sichtbar dadurch, dass es als eines der höchsten Ziele eines Abenteuers angesehen wird, zu vermitteln, dass die NSCs auch ohne die Charaktere ihre Leben leben würden.

* Andere Ansätze

Nachdem wir die zwei Extreme „Wegwerf-Welten“ und „Die eine Welt“ hatten, schauen wir doch kurz noch auf Alternative Ansätze

Gurps bietet den Ansatz gleicher Regeln in vielen Welten, zusammen mit Reisen durch Raum und Zeit, wenn man die Charaktere weiterspielen will. Es liefert Werkzeuge, um eigene Kampagnen zu schreiben und arbeitet diese Werkzeuge mit so vielen Nachforschungen und so viel Sorgfalt aus, dass die Bücher oft bessere Einstiegsquellen für ein Thema sind als ein LExikon - ja, auch besser als Wikipedia, und spannender.

Shadowrun liefert wie DSA eine persistente Welt, aber mit einem stärkeren Fokus auf Ausrüstung - und eben für Cyberpunk und Fantasy in einem.

DnD liefert ein Set von Regeln und Charakterklassen und verkauft Klassenbücher. Das Äquivalent zu Ausrüstungsbüchern in einer Welt mit begrenzten Entwicklungsmöglichkeiten.

Vampire verkaufte Hitergrundbücher. Das konnte nicht gut gehen, wenn die ihren Hintergrund brechen. Sie haben ihre Geldquelle zerschossen.

* Warum ist die Geldquelle wichtig?

Ich habe jetzt viel von der den Geldquellen der Spiele gesprochen, ohne zu sagen, warum sie wichtig sind.

Ein Rollenspiel wird hertzutage entweder im Netz veröffentlicht und als Hobby geschrieben. Oder es wird gedruckt - und auch als Hobby veröffentlicht. Aber es muss halt genug Geld dabei rumkommen, dass sich der druck finanzieren lässt.

Dadurch können nur Werke gedruckt werden, die genug Geld abwerfen, also genug Käufer finden. Diese Hefet sind damit logischerweise das, was die meisten Spieler des Systems mit dem System verbinden. Denn die am meisten gekauften Werke sind meist auch die von den meisten gelesenen.

Grob vereinfacht lässt sich also sagen, dass die Geldquelle eines Rollenspiels sich über kurz oder lang zum Markenzeichen des Spiels entwickeln wird. Daher ist es essenziell zu überlegen, womit du Geld verdienen willst, oder zumindest, was dein Produkt sein soll.

Was ist das, von dem du dir wünscht, dass Leute es bei dir suchen? Das solltest du zu deinem Produkt machen - und versuchen, damit Geld zu verdienen.


