Plot-Point-Kampagnen und nachhaltige Welten

* Was sind PPKs?

Plot Point Kampagnen sind mit Sawage Worlds groß geworden, oder haben zumindest größere Verbreitung erlangt (in Traveller gab es ähnliche Konzepte) und sie haben in der deutschen Netzgemeinde eine starke Anhängerschaft.

Sie sind vorlagen für episches, weltveränderndes Spiel, bei dem der SL grobe Hinweise gegeben werden, mit denen Sie ire Kampagne leiten kann.

Im Kleinen sind sie dadurch ähnlich wie Flyerbücher - was kaum verwundern sollte, wo doch Taysal ein anhänger von Sawage Worlds ist.

Im Großen dagegen unterscheiden sie sich dadurch, dass sie das dramatische Potenzial eines ganzen Settings freisetzen - und verbrauchen.
Zornhau schreibt dazu, dass Sawage Settings mit grober Feder gestrickt sind. Im Kontext dieses Textes könnte man das umformulieren als „Sawage Settings liefern nur die Hintergründe, die nötig sind, um ihre Plot Point Punkte Kampagne zu befeuern“. Und wenn die Kampagne durchgespielt ist, ist entsprechend auch der Hintergrund verbraucht.

Insofern ist hiermit der Hintergrund vollständig der Geschichte untergeordnet, so wie es auch in vielen Romanen passiert.

Für Pinnacle ist diese Stategie sehr geschickt, dadurch dass Welten mit klassischer Plot Punkte Kampagne nur so lange leben, bis die PPK gsspielt ist, wird das Regelwerk zum Fokuspunkt und es gibt stetigen Bedarf an neuen Veröffentlichungen. 

Gleichzeitig werden Settings zum Verbrauchsgegenstand, so dass nicht die Gefahr besteht, dass ein Setting größer wird als sein Regelwerk, was wiederum Sicherstellt, dass die Autoren von Sawage Worlds Hintergruünden an Sawage Worlds gebunden bleiben.

Allerdings ist das auch für die Autoren nützlich, denn ihre Arbeit wird zwar nur einmal erlebt, aber dafür haben ihre Fans Bedarf an weiteren 
