Plot-Point-Kampagnen und nachhaltige Welten

* Was sind PPKs?

Plot Point Kampagnen sind mit Sawage Worlds groß geworden, oder haben zumindest größere Verbreitung erlangt (in Traveller gab es ähnliche Konzepte) und sie haben in der deutschen Netzgemeinde eine starke Anhängerschaft.

Sie sind vorlagen für episches, weltveränderndes Spiel, bei dem der SL grobe Hinweise gegeben werden, mit denen Sie ire Kampagne leiten kann.

Im Kleinen sind sie dadurch ähnlich wie Flyerbücher - was kaum verwundern sollte, wo doch Taysal ein anhänger von Sawage Worlds ist.

Im Großen dagegen unterscheiden sie sich dadurch, dass sie das dramatische Potenzial eines ganzen Settings freisetzen - und verbrauchen.
Zornhau schreibt dazu, dass Sawage Settings mit grober Feder gestrickt sind. Im Kontext dieses Textes könnte man das umformulieren als „Sawage Settings liefern nur die Hintergründe, die nötig sind, um ihre Plot Point Punkte Kampagne zu befeuern“. Und wenn die Kampagne durchgespielt ist, ist entsprechend auch der Hintergrund verbraucht.

Insofern ist hiermit der Hintergrund vollständig der Geschichte untergeordnet, so wie es auch in vielen Romanen passiert.

Für Pinnacle ist diese Stategie sehr geschickt, dadurch dass Welten mit klassischer Plot Punkte Kampagne nur so lange leben, bis die PPK gsspielt ist, wird das Regelwerk zum Fokuspunkt und es gibt stetigen Bedarf an neuen Veröffentlichungen. 

Gleichzeitig werden Settings zum Verbrauchsgegenstand, so dass nicht die Gefahr besteht, dass ein Setting größer wird als sein Regelwerk, was wiederum Sicherstellt, dass die Autoren von Sawage Worlds Hintergruünden an Sawage Worlds gebunden bleiben.

Allerdings ist das auch für die Autoren nützlich, denn ihre Arbeit wird zwar nur einmal erlebt, aber dafür haben ihre Fans Bedarf an weiteren Werken. Und das gibt Rollenspielen eine (weitere, kleine) kommerzielle Perspektive. Und das heißt, dass sie es (teilweise) finanziert kriegen, für Rollenspiele zu schreiben.

Im Endeffekt hat Pinnacle mit PPKs ein Extrem der Kräfteverteilung zwischen Welt und Regeln realisiert: Das Regelwerk als Spielform, zusammen mit Wegwerf-Welten.

* Was sind nachhaltige Welten

Das Gegenstück zu diesem Konzept sind Welten, die immer weiter verfeinert werden, um in der gleichen Welt immer neue Abenteuer und Spielformen finden. Das bekannteste Beispiel dafür ist in Deutschland DSA. Hier wird jeder Fleck der Welt detailliert ausgearbeitet, und diese Regionalbeschreibungen werden verkauft.
Hierdurch entwickelt sich eine immer intensivere Vorstellung der Welt, und wenn die einzelnen Beschreibungen konsistent sind (und gut gemacht), kann sich die Welt für die Spieler zu einer zweiten Heimat entwickeln. Durch dieses Heimatgefühl können dann kleinere Handlungen eine Bedeutung erlangen, die der Rettung der Welt entspricht, ohne aber die Welt zu zerstören. Die Kräfteverteilung zwischen Regeln und Welt ist hier gerade umgekehrt wie bei Plot-Punkte-Kampagnen: DSA-Spieler neigen eher dazu, die Regeln zu ändern (wie an mehreren DSA-Regeln-Klonen sichtbar wird), um das Gefühl von Aventurien zu transportieren, als an der Welt zu schrauben. Und die Pervertierung von beidem durch die Borbaradianer hat mir selbst sehr schwer im Magen gelegen - anders als bei jeglicher anderen Welt.

Außerdem können Spieler in der Welt mit den gleichen Charakteren immer neue Abenteuer erleben und dabei Stück für Stück eine immer stärkere Vorstellung der Welt und auch ihres Charakters aufbauen.

Insofert verkörpert DSA das andere Extrem: Die persistente Welt, vielleicht am stärksten sichtbar dadurch, dass es als eines der höchsten Ziele eines Abenteuers angesehen wird, zu vermitteln, dass die NSCs auch ohne die Charaktere ihre Leben leben würden.


