#+title: Ägypten, Hexen, Magier und Politik: Eine 36h Mystery-Doppelrunde
#+options: toc:nil num:nil 

#+BEGIN_ABSTRACT
Dieses Abenteuer spielt in unserer Welt im Jahr 2014 - mit Magie, alten Geheimbünden und machtvollen Ritualen. Wir haben es auf dem ESW 2014 mit Witchcraft geleitet, es sollte sich allerdings für jedes Regelwerk eignen, das Magie in der Neuzeit abbilden kann. In Witchcraft sind die magischen Effekte überraschend heftig, in der Welt hinter der Welt sind sie deutlich subtiler und mit Shadowrun werden die Konflikte zwischen machtvollen Magierbünden auf Bürgerkiegsniveau ausgetragen. Die Handlung sollte mit all diesen Regelwerken funktionieren, solange die Regelwerke komplexe Rituale ermöglichen, mit denen Macht weit über der verfügbaren Spontanmagie freigesetzt werden kann. Je mächtiger die Charaktere sind, desto mächtiger werden auch die Antagonisten. Wir haben es mit 2 Gruppen gespielt: Einem Bund von Rosenkreuzer Aristokraten und einem zusammengewürfelten Grüppchen Wicca und Solitaires.
#+END_ABSTRACT

#+toc: headlines 2

* Einführung
Wenn der Plan eines Pharaos auf den fruchtbaren Nährboden elitärer Magier fällt und seine Rückkehr an die Spitze der Macht im stärksten Land des alten Europa in greifbare Nähe rückt, müssen selbst Erzfeinde sich zusammenschließen, um die Ordnung, die sie kennen, zu bewahren - wenn sie das wirklich wollen.

Die Ser Rose sind ein alter Bund abtrünniger Rosenkreuzer[fn:3] - Magier, deren Mitglieder meist aus den Kreisen der Reichen und Gebildeten stammen - die anders als ihre Brüder und Schwestern ihren Forscherdrang über jegliche Ethik stellen. Jegliche Hindernisse in ihrem Weg sind für sie ein Übel, das beseitigt werden muss, und als sie vor hundert Jahren auf den Plan des Pharaos Ptolomäus stießen, mit dem dieser eine Welt der Forschung, Kunst, Integration und Magie nach Griechischem Vorbild schaffen wollte, entschiden sie sich, ihn seinen Plänen entsprechend in die heutige Zeit zu holen. 100 Jahre haben sie im Schatten gearbeitet und die magischen und politischen Bedingungen für diesen Plan geschaffen, und nun mit einer schülerin eines Ihrer Mitglieder an der spitze Deutschlands und dem ersten Wirklich redebegabten Bundespräsidenten, dessen vorstellungen von Demokratie fast Deckungsgleich mit denen des Pharaos sind, ist endlich die Zeit für den letzten Schritt gekommen: Die Wiederauferstehung des Pharaos im Körper und mit all den Erfahrungen und Fähigkeiten von Joachim Gauck.

Die Spieler übernehmen die Rolle von Magiern mit nicht unerheblicher Macht, die die Möglichkeit haben, sich dieser Intrige gegen die Demokratie wie wir sie kennen entgegenzustellen.

Der Stil dieses Abenteuers: Mut zur Lücke. Gespielt wird in unserer Welt. Schlag vorher nach, was deine Leute immer fragen. Während dem Spiel kannst du einfach erfinden, was du brauchst. Wenn möglich, frag den oder die in deiner Runde mit dem meisten Hintergrundwissen oder der meisten Erfahrung zu dem Bereich, mit dem ihr gerade zu tun habt - egal ob das nun ein Ort ist oder ein bestimmter Themenbereich. Lass dann einfach ihn oder sie beschreiben (und sag möglichst oft ja, es sei denn, es würde wirklich die Story zerbrechen - versuche selbst in dem Fall lieber “Genau. Aber…” zu sagen - und mit dem Aber nicht die Beschreibung zu widerlegen, sondern eine möglichst spannende Komplikation einzubauen).

* Regeln
Was die Regeln mindestens brauchen: Ritualmagie, die stärker ist als Spruchmagie, aber die richtige Zeit, den richtigen Ort Ort und Ritualgegenstände benötigt.
* Die Gegenspieler
* Zwei Gruppen
Eine Loge Roleskreuzer und ein Häuflein Heiden, Wicca (Hexen) und Spinner.
* Grundlagen zum Leiten mit zwei Gruppen
* Vorgeschichte
- Gestorbene Bankräuber hat eine Nekromantin, die ihn liebte, übernommen. Sie hat seinen Geist in ihren Körper gerufen, jetzt will er nicht mehr gehen. Sein Wille ist viel stärker als ihrer. Je nach Regeln erkennt sie dadurch, dass er sie nicht liebt, sondern nur benutzt.

* Zeitablauf
/Für 2 Runden. Wir haben im ersten und dritten Teil explizit keine festen Datumsangaben verwendet, um trotz sicher unterschiedlicher In-Play-Zeit den ersten Kontaktpunkt gemeinsam erreichen zu können. Das einzige Datum, das feststeht, ist der 30.4.: Das Ägyptische Beltaine. Den Spielern und Spielerinnen haben wird das offen gesagt. Sie werden gebeten, uns Zeitzerzerrungen, Zeitsprünge und harte Schnitte zuzugestehen. Bei Doppelrunden sind bestimmte Freiheiten sehr nützlich, um eine gemeinsame Geschichte erschaffen zu können. Von langweiligen Wartezeiten, während denen eine Gruppe völlig ausgebremst ist, hat niemand was./

** Wald bei Bonn
*** Ser Rose
*** Rosenkreuzer
Ein Diebstahl im Museum oder einer Privatsammlung (vielleicht gehört es einem der Charaktere oder Bekannten). Detektivarbeit ⇒ Das Museum und die Ägyptischen Artefakte.

Darunter eine Schriftrolle von Phtolomäus. Führt zu einem Ritualplatz. Der Dieb in der Magierin denkt, hier nur den Körper bleibend gegeben zu bekommen, stört aber mehrfach durch Ungeduld und Aggressionen das Ritual.

Am Ende: Ein Blatt der Schriftrolle fehlt (am Ritualplatz).
*** Wicca und Solitaires
Ein Waldstück bei Bonn. Gruppenzusammenführung ⇒ Der Wald, Das Ritual und die Nebenwirkungen.

- Gruppenzusammenführung: Frag sie, was sie zu dem Wald bringen könnte. Durch das Ritual werden Handies gestört (und später vielleicht zerstört - inklusive aller gespeicherten Daten - wenn das notwendig ist, um stetige Kommunikation zwischen den beiden Gruppen zu verhindern[fn:2]), Leute in der Nähe des Waldes werden entweder völlig passiv oder verschwinden und selbst Motoren, die zur falschen Zeit an einem Ort sind, an dem sich Verzerrung der Realität durch die wiederholte Störung des Rituals fokussiert (also alle, bei denen es wichtig ist, damit die Spieler da landen[fn:1]), hören auf zu funktionieren.

Die Verzerrungen der Realität sind die Auswirkung der Störung des Rituals durch den Dieb.

** Der Brocken bei Hildesheim: Ein Ägyptisches Beltaine

*** Zivilisten
*** Wie das Ritual funktioniert
*** Magische Kämpfe
*** Der Brocken

** Berlin Dungeon
* Kontaktpunkte der beiden Gruppen

** Trennungen

(wichtiger noch als die Kontaktpunkte: Die Gruppen wieder entkoppeln, damit sie nicht aufeinander warten müssen)

- Nach Bonn gehen alle Kommunikationsmittel der Wicca durch die Nebenwirkungen des von dem Dieb gestörten Rituals kaputt. Inklusive aller Aufzeichnungen von Kontaktmöglichkeiten mit den Rosenkreuzern. Sei offen zu deinen Spielern: Das ist notwendig, um gut spielen zu können. Erarbeitet gemeinsam Lösungen für logische Brüche.

- Nach dem Brocken werden die Rosenkreuzer unter absoluter Verschwiegenheit in ihren Orden gerufen.

* Wie es weitergeht
(oder weitergehen kann)
* Personen und Spielorte
** Die Ser Rose
** Kontaktpersonen
** Spielercharaktere
* Das Abenteuer als Kampagne
* Spielbericht

* Footnotes

[fn:1] Für alle, die jetzt „Railroading“ schreien empfehle ich eine vollständig zufällige Vorgehensweise: 20 magisch begabte Charaktere in der Nähe des Waldes und würfelt aus, wen es trifft. Die Spieler und Spielerinnen würfeln dann aus, welchen der Leute sie spielen, die für die Handlung zufälligerweise wichtig werden. Wir haben uns die Charaktere erschaffen, die für die Geschichte wichtig sein sollen, die also in der Nähe des Rituals auf die anderen treffen werden. Die Zusammenführung erklärt nur, wie das passiert ist.

[fn:2] Wir müssen die Kommunikation zwischen den Gruppen unterbrechen, damit sie nicht zu eng gekoppelt sind. Nur so lassen sich nervige Wartezeiten durch unterschiedliche Geschwindigkeit verschiedener Handlungen vermeiden.

[fn:3] Die grundlegenden Ideen zu den Gruppierungen stammen aus Witchcraft von Eden Studios.
