#+title: Für eine nachhaltige Welt
#+options: toc:nil num:nil
#+author: KGE
#+date: 19. April 2014

Liebe Brüder und Schwestern im Geiste,

Wir streben nach der Reetablierung der Demokratie nach griechischem Vorbild und der Beendigung der Tyrannei der Masse. Nicht mehr länger sollen die Gebildeten dem Pöbel dienen müssen. In den letzten hundert Jahren hat die Ideologie der Demokratie einen beispiellosen Siegeszug erlebt. Und die Massaker, die in der Welt in ihrem Namen verübt werden, der beispiellose Raubbau an unseren Lebensgrundlagen und die immer weiter steigende Macht der neureichen Emporkömmlinge zeichnen ein klares Bild von dem Nutzen dieser Staatsform.

Der Pöbel ist weder in der Lage, nachhaltige Entscheidungen zu treffen, noch die Grundlagen seiner eigenen Macht zu verteidigen. Doch zumindest letzteres wird uns zum Wohle gereichen: Der Pöbel wird allen folgen, die ihn führen, und wir können ihn in unserem Interesse lenken. Würden wir jedoch das Prinzip der Pöbelherrschaft behalten, müssten wir stetig mit Marktschreiern in Konkurrenz um die Macht treten, was uns die Verfolgung höherer Ziele unmöglich mächte. Daher müssen wir die Demokratie zu ihrer eigentlichen Bedeutung zurückführen: Haben die alten Griechen nicht auch Sklaven gehalten? Wäre es ihnen jemals in den Sinn gekommen, diesen Sklaven eine Stimme zu geben? Natürlich nicht! Und genau wie bei den alten Griechen nur wählen durfte, wer sich der Stimme würdig erwiesen hatte, so soll nur noch über die Zukunft bestimmen, wer bewiesen hat, dass er oder sie diese Verantwortung zu würdigen weiß.

Unsere Brüder haben die Gefahren der Pöbelherrschaft früh erkannt. Sir Churchill wird zitiert mit der Aussage „Die Demokratie ist die schlechteste Staatsform, ausgenommen aller anderen“. Viele schreiben ihm zu, ein Rosenkreuzer gewesen zu sein, und kaum jemand wundert sich, warum seine privaten Aufzeichnungen nicht in den Archiven der Rosenkreuzer zu finden sind. Entsprechend kennt kaum jemand die Hintergründe seiner Aussage. Um in den Grenzen der Möglichkeiten der Krone gegen die Nazis bestehen zu können, brauchten sie den Pöbel, und der Pöbel musste gefüttert werden. Um dies zu erreichen, strich unser Bruder den zweiten Teil seines Satzes: „…, die der beschränkte Geist des Pöbels zu würdigen weiß“. Dem Experiment unseres Bruders Sir Churchill und seiner Vertrauten war nur kurzzeitiger Erfolg beschieden, denn nachdem sich ihre Nachfolger größeren Fragen zuwandten als der Verwaltung der Dummheiten des Pöbels, brach ihre Vision einer Welt der freien Wissenschaft zusammen. Doch in der Technik, den Pöbel kleinzuhalten, sind ihre Nachfolger auf der Insel und auf dem neuen Kontiinent bis heute ungeschlagen.

Hier im kontinentalen Europa arbeiten wir seit dieser Zeit an einem eigenen Plan, und seit wir mit der Wiedervereinigung Deutschlands den nutzlosen Konflikt der Ideologien beilegen konnten, tragen unsere Pläne für eine vernunftgesteuerte Gesellschaft im alten Deutschland immer mehr Früchte.

Die Partei der Grünen, einstmals Spinner und Radikale, doch bis vor kurzem unser bestes Werkzeug, brachten die soziale Verblendung in Einklang mit dem Selbsthass des Pöbels: Zusammen mit den selbsternannten Arbeiterführern schufen sie die Enteignungsmaschine, die die ungebildeten Klassen endlich wieder vor dem Abstieg zittern lässt. Heute sind selbst Sklaven noch froh, eine Aufgabe zu haben, da sie so zumindest nicht ihre Familie belasten. Obwohl sie nicht die Aufrichtigkeit besaßen, würdige Gebildete von dieser Maschine auszunehmen, legten sie damit einen der wichtigsten Grundpfeiler unseres heutigen Plans. Der Köder der Rückkehr zum Militarismus, den wir dafür den alten Mächten zuwerfen mussten, war ein verschmerzbares Übel - und wird sich für unsere Ziele vielleicht als nützlich erweisen, auch wenn er natürlich Arbeitskraft bindet, die besser anderem gewidmet wäre. Bedenkt das Schicksal der Bibliothek von Alexandria: Auch die beste Staatsform muss wehrhaft sein. Die Gefahren eines Putsches durch den Pöbel sind nicht zu unterschätzen, wie das Schicksal vieler der Vasallenstaaten im Süden zeigt. Hier im alten Deutschland konnten wir ihn durch den Sohn der Guttenbergs abfangen. Seit nun die Schülerin unseres Bruders Zülich an der Macht ist und gemeinsam mit den Grünen den gewandtesten Fürsprecher der griechischen Demokratie ins höchste Amt gebracht hat, kommen unsere Pläne in die letzte Phase. Nur noch ein paar Jahre, dann werden wir erst in Deutschland und dann in Europa die ursprüngliche Form der Demokratie wiederbeleben. Hier haben wir die einzigartige Chance, eine Herrschaft der Würdigen zu etablieren, ohne mit Popularisten koalieren zu müssen. Die Folgen solch kurzsichtiger Koalitionen sehen wir dieser Tage in Russland, wo die Integration aller Kulturen im Geist der allumfassenden Bildung an den Kirchenfreunden und den Jugendbanden Putins zerbricht. Diese Gefahr bietet sich in unserem Land zum Glück noch nicht, doch wir müssen schnell sein, denn wenn die Pläne der Technokraten und Emporkömmlinge noch weitere Früchte tragen und den Hass der Halbgebildeten auf die alten Künste noch weiter schüren und ihm im Internet einen Kraftort schaffen, an dem persönliches Erleben keine Macht hat, dann werden wir wieder Hexenjagden erleben. Und diesmal würden sie nicht nur die Wicca treffen: Mit den neuen Möglichkeiten werden sie uns finden.

Darum ist es Zeit, die alten Feindseligkeiten zu begraben.

Jahrtausende lang haben wir uns vor euch verborgen, doch nun bitten wir euch, unsere Brüder und Schwestern, uns in diesem wichtigsten Kampf für eine unserer Kunst zuträgliche Zukunft zu unterstützen. In wenigen Tagen wird die Entscheidung fallen, ob die Zukunft der Welt von Gebildeten oder von Ideologen geformt wird. Bedenket die Weisheit, die wir in der Bildung der Massen verankern konnten, und helft uns, die Vision der alten Griechen zu verwirklichen:

#+BEGIN_QUOTE
Verstand ist stets bei wenigen nur gewesen — Friedrich von Schiller.
#+END_QUOTE

Gezeichnet,\\
KGE

Im Anhang: Pläne für Unterstützungsritualen in jeder größeren Stadt Deutschlands.

/Anmerkung: Dieser Text ist ein Fiktionales Werk mit politischer
Satire. Er wurde nicht wirklich von KGE geschrieben, sondern von Arne
Babenhauserheide für eine 24h Doppel-Rollenspielrunde, die er am
19.4. am Extremspielwochenende mit Alexander Fuß geleitet hat. Teile
des Inhalts sind frei erfunden, andere sind wahr, doch selbst die
wahren Aussagen werden genutzt, um eine zutiefst verachtenswürdige
Ideologie zu unterstützen, von der wir uns ausdrücklich
distanzieren. Wir verwenden diese Ideologie als Handlungsmotor, denn
was wäre eine Geschichte ohne starke Antagonisten. Die Seite [[http://1w6.org][1w6.org]]
liefert Einzelheiten./

* Magisch                                                          :noexport:

/Nicht wichtlich, was wir gespielt haben (wir haben deutlich gekürzt), könnte aber spannend sein, wenn ihr die Runde zu einer Kampagne ausbauen wollt./

Destabilisierung der Zeit in Berlin, um den Geist von Ptolomäus in die Gegenwart rufen zu können ⇒ Den Geist in den Körper von Gauck bannen. Dafür muss Gauck plastiniert werden. ⇒ Überfall auf dern Gründer der „Körperwelten“

Jedes Ritual braucht ein Opfer, durch das Große Mengen an Essenz freigesetzt werden. Diese Essenz wird genutzt, um ein Siegel in die Wirklichkeit zu schreiben, das die Zeit destabilisiert.

Um Alte und Neue Zeiten zu verbinden, reißt das Siegel ein POrtal zur Welt eines alten Äpyptischen oder griechiscneh Gottes auf, der so Einfluss auf einen kleinen Teil der Welt erhält. Dessen Diener schwärmen aus, um die Bedrohungen für das Tor unschädlich zu machen: Magier. Die Das öffnen des Tores ist aber nur ein Nebeneffekt: Das Siegel bleibt für Jahr und Tag bestehen.

Wenn die charaktere wissen, dass die Siegel dazu dienen, die Macht des Serabis zugänglich zu machen, könnten sie sogar mit einem Dienerwesen der Anderen Götter reden: Für alle 4 Götter ist Serapis eine Bedrohung: Hades, Zeus, Seth, Osiris. (Seth könnten wir auch weglassen - durch Isis haben wir einen zweiten Vertreter aus Ägypten drin, und Hades ist Seth doch recht ähnlich. Besser vielleicht: Hades und Seth zusammen rufen)

Es sieht wie ein Ritual für diese Götter aus, ist aber in Wirklichkeit eine Schändung: Sie werden erst gerufen und dann geschwächt, damit Serapiis zusätzliche Macht erhält. Das ist ihr zweiter Grund, um auf Magierjagd zu gehen. Und ein Grund, warum der Stellvertreter den SCs helfen könnte.

Serapis’ Ehefrau Isis: die könnte Osiris Probleme machen, weil sie durch Serapis viel mächtiger wurde, könnte aber auch Serapis Probleme machen, weil sie später wichtiger wurde als er. Göttin der Geburt, der Wiedergeburt
und der Magie, aber auch Totengöttin. Die heutige Marienverehrung sieht gar nicht so anders aus als Isis, und auch die Göttin der Wicce ist ihr nicht so unähnlich… Laut Wikipedia ist sie sogar sehr nahe an Marienbildnissen, nur dass sie halt nicht Jesus, sondern Horus stillt: „Ab dem Mittleren Reich sind Figurinen bekannt, die Isis mit dem kleinen Horusknaben zeigen. Horus sitzt auf Isis' Schoß und wird von ihr gestillt. Es wird angenommen, dass diese figürliche Darstellung das spätere Christentum zu zahlreichen, bekannten Madonnenbildnissen inspirierte.“


Idee zur Struktur: Jedes Ritual wird von 3 kleineren Ritualen eingeleitet, in denen die gerade nicht gerufenen Götter in kleinen Vororten gebunden werden. Ein Gleichseitiges Dreieck, in dessen Zentrum dann das wirkliche Ritual stattfindet. Eigentlich ein Tetraeder: Der gerufene Gott ist die nach oben zeigende Spitze. Der Tetraeder wird „gekippt“ und so auf Berlin zubewegt.Es gibt anfangs noch viele Möglichkeiten, ungerufene Götter zu wählen, aber beim 4. Ritual bleibt nur noch eine Richtung, (ich muss noch auf einer Karte schauen, ob das so funktioniert)

Die kleineren Rituale sind für Suchende klar erkennbar: Sie erzeugen schon Wellen in der Essenz. Idee: Durch ihre große Nähe zum ersten Ritual wurden die Charaktere gezeichnet, so dass sie viel empfänglicher für diese Wellen wurden. Daher sind sie die logische Wahl für die Untersuchung der Vorfälle (deswegen mischen sich nicht plötzlich hunderte andere Gifted ein).

* Politisch                                                        :noexport:

Nach der Auflösung der ideologischen Gräben durch die Wiedervereinigung Deutschlands ist es an der Zeit, die ideologisch verbrämte Pöbelpolitik durch eine wissenschaftlich fundierte Politik der Würdigen zu ersetzen.

** Mitglieder der Ser Rose in der Politik

*** Grüner Staatssekretär

Das Wahlprogramm 2013 hat gezeigt, dass die Grüne Basis zu stark vom Pöbel kontrolliert wird, so dass die Grünen untauglich sind als Material für eine wahre Demokratie nach griechischem Vorbild (mit Sklaven). Die Nachhaltigkeits- und Integrationsideen der Grünen in die CDU unter Merkel integrieren und dann die Grünen von innen abschießen.

*** Eine Professorin von Merkel

Sie hat Zugang zu allen hohen Personen in der Politik und Merkel hört auf sie.

Merkels Vater studierte Theologie in Heidelberg…

Die Arbeit von Merkel über Marxismus-Leninismus (Teil ihrer Doktorarbeit) wurde von Professor Rittershaus begleitet und ist verschollen.

Notizen zu Merkel als mögliche Stasi-Informantin: http://de.guttenplag.wikia.com/wiki/Forum:Vergleich_der_Diplomarbeit_mit_der_Doktorarbeit_von_Angela_Merkel#mw-content-text

Bundespräsident Gauck arbeitete dort - wir brauchen also nur Gauck, um Merkel zu kontrollieren.

** Der Ser Rose Hörige in der Politik

*** Die Familie Mohn

- Stiftung Bertelsmann
- RTL (erreicht den Pöbel)
- Spiegel (erreicht die halbgebildeten Möchtegern-Eliten)

*** Die Familie Guttenberg

- Springer (über BILD: da arbeitet ein Guttenberg)
- Abschreiber Guttenberg: Hat die Wehrpflicht aufgelöst.

*** Gauck

Schon in der DDR: Sie haben ihm versprochen, er könnte seine eigenen Verfehlungen verschwinden lassen, wenn er der alte Opposition der DDR in den Rücken schießt. Er wurde Chef der Stasi-Behörde. Aber er weiß nicht, ob sie nicht vorher Unterlagen gesichert haben. Dankbar und besorgt zugleich - das perfekte Werkzeug. Und er bietet alles, was Ptolomäus braucht, um in dieser Welt sofort den Zugang zur Macht zu haben, den sie brauchen, um ihre Ziele rechtzeitig zu erreichen.

* Aufruf                                                           :noexport:

Liebe Brüder und Schwestern im Geiste,

Wir streben nach der Reetablierung der Demokratie nach griechischem Vorbild und der Beendigung der Tyrannei der Masse. Nicht mehr länger sollen die Gebildeten dem Pöbel dienen müssen. In den letzten hundert Jahren hat die Ideologie der Demokratie einen beispiellosen Siegeszug erlebt, und die Massaker, die in der Welt in ihrem Namen verübt werden, der beispiellose Raubbau an unseren Lebensgrundlagen und die immer weiter steigende Macht der neureichen Emporkömmlinge zeichnen ein klares Bild von dem Nutzen dieser Staatsform.

Der Pöbel ist weder in der Lage, nachhaltige Entscheidungen zu treffen, noch die Grundlagen seiner eigenen Macht zu verteidigen. Doch zumindest letzteres wird uns zum Wohle gereichen: Der Pöbel wird allen folgen, die ihn führen, und wir können ihn in unserem Interesse lenken. Würden wir jedoch das Prinzip der Pöbelherrschaft behalten, müssten wir stetig mit Marktschreiern in Konkurrenz um die Macht treten, was uns die Verfolgung höherer Ziele unmöglich mächte. Daher müssen wir die Demokratie zu ihrer eigentlichen Bedeutung zurückführen: Haben die alten Griechen nicht auch Sklaven gehalten? Wäre es ihnen jemals in den Sinn gekommen, diesen Sklaven eine Stimme zu geben? Natürlich nicht! Und genau wie bei den alten Griechen nur wählen durfte, wer sich der Stimme würdig erwiesen hatte, so soll nur noch über die Zukunft bestimmen, wer bewiesen hat, dass er oder sie diese Verantwortung zu würdigen weiß.

Unsere Brüder haben die Gefahren der Pöbelherrschaft früh erkannt. Sir Churchill wird zitiert mit der Aussage „Die Demokratie ist die schlechteste Staatsform, ausgenommen aller anderen“. Viele schreiben ihm zu, ein Rosenkreuzer gewesen zu sein, und kaum jemand wundert sich, warum seine privaten Aufzeichnungen nicht in den Archiven der Rosenkreuzer zu finden sind. Entsprechend kennt kaum jemand die Hintergründe seiner Aussage. Um in den Grenzen der Möglichkeiten der Krone gegen die Nazis bestehen zu können, brauchten sie den Pöbel, und der Pöbel musste gefüttert werden. Um dies zu erreichen, strich unser Bruder den zweiten Teil seines Satzes: „…, die der beschränkte Geist des Pöbels zu würdigen weiß“. Dem Experiment unseres Bruders Sur Churchill und seiner Vertrauten war nur kurzzeitiger Erfolg beschieden, denn nachdem sich ihre Nachfolger größeren Fragen zuwandten als der Verwaltung der Dummheiten des Pöbels, brach ihre Vision einer Welt der freien Wissenschaft zusammen. Doch in der Technik, den Pöbel kleinzuhalten, sind ihre Nachfolger auf der Insel und auf dem neuen Kontiinent bis heute ungeschlagen.

Hier im kontinentalen Europa arbeiten wir seit dieser Zeit an einem eigenen Plan, und seit wir mit der Wiedervereinigung Deutschlands den nutzlosen Konflikt der Ideologien beilegen konnten, tragen unsere Pläne für eine vernunftgesteuerte Gesellschaft im alten Deutschland immer mehr Früchte.

Die Partei der Grünen, einstmals Spinner und Radikale, doch bis vor kurzem unser bestes Werkzeug, brachten die soziale Verblendung in Einklang mit dem Selbsthass des Pöbels: Zusammen mit den selbsternannten Arbeiterführern schufen sie die Enteignungsmaschine, die die ungebildeten Klassen endlich wieder vor dem Abstieg zittern lässt. Heute sind selbst Sklaven noch froh, eine Aufgabe zu haben, da sie so zumindest nicht ihre Familie belasten. Obwohl sie nicht die Aufrichtigkeit besaßen, würdige Gebildete von dieser Maschine auszunehmen, legten sie damit einen der wichtigsten Grundpfeiler unseres heutigen Plans. Der Köder der Rückkehr zum Militarismus, den wir dafür den alten Mächten zuwerfen mussten, war ein verschmerzbares Übel - und wird sich für unsere Ziele vielleicht als nützlich erweisen, auch wenn er natürlich Arbeitskraft bindet, die besser anderem gewidmet wäre. Bedenkt das Schicksal der Bibliothek von Alexandria: Auch die beste Staatsform muss wehrhaft sein. Die Gefahren eines Putsches durch den Pöbel sind nicht zu unterschätzen, wie das Schicksal vieler der Vasallenstaaten im Süden zeigt. Hiier im alten Deutschland konnten wir ihn durch den Sohn der Guttenbergs abfangen. Seit nun die Schülerin unseres Bruders Zülich an der Macht ist, kommen unsere Pläne in die letzte Phase. Nur noch ein paar Jahre, dann werden wir erst in Deutschland und dann in Europa die ursprüngliche Form der Demokratie wiederbeleben. Hier haben wir die einzigartige Chance, eine Herrschaft der Würdigen zu etablieren, ohne mit Popularisten koalieren zu müssen. Die Folgen solch kurzsichtiger Koalitionen sehen wir dieser Tage in Russland, wo die Integration aller Kulturen im Geist der allumfassenden Bildung an den Kirchenfreunden und den Jugendbanden Putins zerbricht. Diese Gefahr bietet sich in unserem Land zum Glück noch nicht, doch wir müssen schnell sein, denn wenn die Pläne der Technokraten und Emporkömmlinge noch weitere Früchte tragen und den Hass der Halbgebildeten auf die alten Künste noch weiter schüren und ihm im Internet einen Kraftort schaffen, an dem Persönliches erleben keine Macht hat, dann werden wir wieder Hexenjagden erleben. Und diesmal würden sie nicht nur die Wicca treffen: Mit den neuen Möglichkeiten werden sie uns finden.

Darum ist es Zeit, die alten Feindseligkeiten zu begraben.

Jahrtausende haben wir uns vor euch verborgen, doch nun bitten wir euch, unsere Brüder und Schwestern, uns in diesem wichtigsten Kampf für eine unserer Kunst zuträgliche Zukunft zu Unterstützen. In wenigen Tagen wird die Entscheidung fallen, ob die Zukunft der Welt von Gebildeten oder von Ideologen geformt wird. Bedenket die Weisheit, die wir in der Bildung der Massen verankern konnten, und helft uns, die Vision der alten Griechen zu verwirklichen:

#+BEGIN_QUOTE
Verstand ist stets bei wenigen nur gewesen — Friedrich von Schiller.
#+END_QUOTE

Gezeichnet,
KGE

